# To install the git pre-commit hooks run:
#   prek install --install-hooks --overwrite
# To update the versions:
#   prek autoupdate
exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg)(/|$)'
# Note the order is intentional to avoid multiple passes of the hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: main
    hooks:
      - id: ruff
        # Using --unsafe-fixes can change code behavior
        args: [--fix, --exit-non-zero-on-fix, --show-fixes{% if cookiecutter.ruff_unsafe_fixes %}, --unsafe-fixes{% endif %}]
      - id: ruff-format
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: main
    hooks:
      - id: tombi-format
        # args: [ "--offline" ]
      - id: tombi-lint
        # args: [ "--offline" ]
    # Should you use this offline, uncomment those args
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
      - id: trailing-whitespace
{%- if cookiecutter.c_extension_support == 'cython' %}
        exclude_types:
          - c
{%- endif %}
      - id: end-of-file-fixer
{%- if cookiecutter.c_extension_support == 'cython' %}
        exclude_types:
          - c
{%- endif %}
      - id: mixed-line-ending
      - id: debug-statements
